# Generated by Django 3.1.7 on 2021-03-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210303_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Local do Evento'),
        ),
    ]
